name: Build and push image to GAR
on:
  release:
    types: [created]
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AUTOMATION_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AUTOMATION_AWS_SECRET_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_AUTOMATION_ROLE_ARN }}
          role-duration-seconds: 900
      - name: set aws auth outputs
        id: auth
        shell: bash
        run: |
          echo "::set-output name=awsAccessKeyId::$AWS_ACCESS_KEY_ID"
          echo "::set-output name=awsSecretAccessKey::$AWS_SECRET_ACCESS_KEY"
          echo "::set-output name=awsSessionToken::$AWS_SESSION_TOKEN"
      - uses: swarm-io/action-build-push-image@v1
        with:
          credentials-json: ${{ secrets.GAR_WRITE_SERVICE_ACCOUNT_KEY }}
          project-id: ${{ secrets.GCLOUD_PROJECT_ID_PROD }}
          secrets: |
            GIT_PAT=${{ secrets.GIT_RUNNER_TOKEN }}
            AWS_ACCESS_KEY_ID=${{ steps.auth.outputs.awsAccessKeyId }}
            AWS_SECRET_ACCESS_KEY=${{ steps.auth.outputs.awsSecretAccessKey }}
            AWS_SESSION_TOKEN=${{ steps.auth.outputs.awsSessionToken }}
