name: Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/ui-admin-angular/**'
jobs:
  build:
    if: github.event.pull_request.draft == false
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10'
          cache: 'yarn'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AUTOMATION_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AUTOMATION_AWS_SECRET_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_AUTOMATION_ROLE_ARN }}
          role-duration-seconds: 900
      - name: Compile App
        run: |
          yarn run co:login
          yarn install
          yarn run build-production
