name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'apps/ui-admin-angular/**'
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release and update helm chart
    steps:
      - uses: catalystsquad/action-semantic-release-general@v1
        with:
          token: ${{ secrets.GIT_RUNNER_TOKEN }}
          release-config: "@catalystsquad/release-config-general"