name: Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'skaffold.yaml'
jobs:
  validate-pr-title:
    name: Validate PR Title
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: amannn/action-semantic-pull-request@v3.4.6
        with:
          types: |
            fix
            feat
            norelease
        env:
          GITHUB_TOKEN: ${{ github.token }}
  compile:
    if: github.event.pull_request.draft == false
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10'
          cache: 'yarn'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AUTOMATION_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AUTOMATION_AWS_SECRET_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_AUTOMATION_ROLE_ARN }}
          role-duration-seconds: 900
      - name: Compile App
        run: |
          yarn run co:login
          yarn install
          yarn run build-production
