name: Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/ui-admin-angular/**'
jobs:
  release:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AUTOMATION_AWS_ACCESS_KEY_ID_SWARM }}
          aws-secret-access-key: ${{ secrets.AUTOMATION_AWS_SECRET_ACCESS_KEY_SWARM }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AUTOMATION_AWS_ROLE_ARN_SWARM }}
          role-duration-seconds: 900
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: apps/ui-admin-angular/package-lock.json
      - name: build production release
        working-directory: apps/ui-admin-angular
        run: |
          npm run co:login
          npm ci
          npm run build-prod
