name: UI Beef Deploy
on:
  release:
    types:
      - published
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Run production build and create a github release with the zipped production build
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AUTOMATION_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AUTOMATION_AWS_SECRET_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_AUTOMATION_ROLE_ARN }}
          role-duration-seconds: 900
      - uses: hashicorp/setup-terraform@v2
      - name: fetch release assets
        uses: robinraju/release-downloader@v1.7
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          fileName: release.zip
          out-file-path: infra/terraform/ui-beef/dist
      - name: unzip distribution for upload to s3
        working-directory: ./infra/terraform/ui-beef/dist
        run: |
          pwd
          unzip release.zip
          rm release.zip
          ls -l
      - name: Terraform Apply
        working-directory: ./infra/terraform
        run: |
          pwd
          ls -l
          terraform init
          terraform apply -target=module.ui-beef-dev -auto-approve