name: UI Beef Deploy
on:
  release:
    types:
      - published
jobs:
  deploy1:
    runs-on: ubuntu-latest
    name: Run production build and create a github release with the zipped production build
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - name: fetch release assets
        uses: robinraju/release-downloader@v1.7
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          fileName: "*"
      - run: |
          ls -l
  deploy2:
    runs-on: ubuntu-latest
    name: Run production build and create a github release with the zipped production build
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - name: fetch release assets
        uses: robinraju/release-downloader@v1.7
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          fileName: release.zip
      - run: |
          ls -l